### ISSUE TITLE
RuntimeError: DOM is not defined

### ISSUE THREAD

**Issue by ertle** [observablehq/notebook-runtime#122]
> If builtins is specified, each property on the builtins object defines a builtin variable for the runtime; these builtins are available as named inputs to any defined variables on any module associated with this runtime 

Unfortunately, I get an error: "RuntimeError: DOM is not defined"  ;(

```js
Runtime.load(notebook, { data }, cell => { 
      if (cell.name === 'chart') {
        return new Inspector(this.ref.nativeElement);
      }
});
```

is there a way to set builtin variables, and render notebook into DOM element?

**Comment by benatkin** [comment]
I got the same issue with `md`. I fixed it by adding this:

``` js
notebook.modules[Object.keys(notebook.modules)[0]].variables.push({name: 'md', value: () => library.md})
```

Perhaps you could fix it by adding this:

``` js
notebook.modules[Object.keys(notebook.modules)[0]].variables.push({name: 'DOM', value: () => library.DOM})
```

It's a temporary hack, likely to break when it's fixed.

**Comment by benatkin** [comment]
I wanted to replace my md to get it to do what I wanted under node with jsdom. Here's my whole file so far (`build.mjs` run with `node --experimental-modules build/build.mjs`):

``` js
import jsdom from 'jsdom'
import fetch from 'node-fetch'
const DOM = new jsdom.JSDOM(``, { pretendToBeVisual: true })
global.window = DOM.window
global.document = DOM.window.document
global.requestAnimationFrame = DOM.window.requestAnimationFrame.bind(DOM.window)
global.fetch = fetch
import notebookRuntime from '@observablehq/notebook-runtime'
import notebook from '../notebook'

const {Runtime, Library} = notebookRuntime
const library = new Library()
const md = (strs, ...vars) => { let s = ''; for (let i=0; i < strs.length; i++) { s += strs[i] + vars[i] || '' }; return s }
notebook.modules[Object.keys(notebook.modules)[0]].variables.push({name: 'md', value: () => md})
Runtime.load(notebook, library, variable => {
  return {
        pending: () => {
          console.log(`loading ${variable.name}`)
        },
        fulfilled: value => {
          console.log(`loaded ${variable.name}:`, value)
        },
        rejected: err => {
          console.error(`error loading ${variable.name}:`, err)
      console.error(err.trace)
        }
  };
});
```

**Comment by tmcw** [comment]
Hey @ertle - the code you're posting -

```js
Runtime.load(notebook, { data }, cell => { 
      if (cell.name === 'chart') {
        return new Inspector(this.ref.nativeElement);
      }
});
```

Given the function signature of [Runtime.load(notebook, [builtins], observer)](https://github.com/observablehq/notebook-runtime#Runtime_load), this is defining `builtins` as an object like `{ data }` (or what ES6 interprets as `{ data: data }`. I'm guessing that you want `data` to be one of the builtins - if that isn't the case, just remove the function argument entirely. But if that is what you want, you can _combine_ the default Library with the custom data property:

```js
Runtime.load(notebook, Object.assign({}, new Library, { data }), cell => { 
      if (cell.name === 'chart') {
        return new Inspector(this.ref.nativeElement);
      }
});
```

And then you should be rid of the DOM is not defined bug. The Library includes all of the default builtins, one of which is DOM, and by providing an alternative data-only builtins object, the example you posted was missing DOM.

This solution is probably the same for @benatkin - it's better to extend the builtins by adding `md` to an extended library than it is to define a new cell.

**Comment by benatkin** [comment]
@tmcw the Library has `md`, though - it seems to expect it to be defined in the notebook. I'm about to post my whole project to the Observable forum, so you can have a look at it then.

**Comment by benatkin** [comment]
Maybe since my cells are defined as `md\`foo\`` rather than `{ return md\`foo\` }` it's adding `md` to the `inputs` in each cell that uses it. or maybe it's actually the reverse...

**Comment by tmcw** [comment]
Here's a worked example of redefining `md` as something runnable in a node environment:

```js
import marked from "marked";
import jsdom from "jsdom";
import fetch from "node-fetch";
const DOM = new jsdom.JSDOM(``, { pretendToBeVisual: true });
global.window = DOM.window;
global.document = DOM.window.document;
global.requestAnimationFrame = DOM.window.requestAnimationFrame.bind(
  DOM.window
);
global.fetch = fetch;
import notebookRuntime from "@observablehq/notebook-runtime";
import notebook from "./notebook";

const { Runtime, Library } = notebookRuntime;
const library = new Library();
const md = (strs, ...vars) => {
  let s = "";
  for (let i = 0; i < strs.length; i++) {
    s += strs[i] + (vars[i] || "");
  }
  return marked(s);
};

Runtime.load(notebook, { ...library, md: Promise.resolve(md) }, variable => {
  return {
    pending: () => {
      console.log(`loading ${variable.name}`);
    },
    fulfilled: value => {
      console.log(`loaded ${variable.name}:`, value);
    },
    rejected: err => {
      console.error(`error loading ${variable.name}:`, err);
      console.error(err.trace);
    }
  };
});
```

`md` won't work off the bat because it uses `d3-require` to lazily load `marked` - same with the tex literal - right now node.js compatibility is not in scope for notebook-runtime or notebook-stdlib, so this is all a bit wild west.

**Comment by benatkin** [comment]
@tmcw thanks! That makes sense. I knew I was missing something.

[I just posted my notebook.](https://talk.observablehq.com/t/building-an-npm-module-with-observable/970)
