### ISSUE TITLE
RuntimeError: visibility is not defined

### ISSUE THREAD

**Issue by alfa07** [observablehq/notebook-runtime#130]
I am embedding a notebook (https://gist.github.com/alfa07/e1fe4b39aefb373559a622180b895498) and one of the cells is rendered into a tab which is not visible. Inside the cell I have:
``
visibility().then(() => ..)
``
Which works fine in the notebook when it is not embedded but when it is embedded I am getting
``
RuntimeError: visibility is not defined
``

**Comment by tmcw** [comment]
Hi Maxim,

That page is using 1.0.1 of notebook-runtime: if you update to the current version (1.2.3) or specify the current major version only (1), it'll work correctly:

```js
import {Inspector, Runtime} from "https://unpkg.com/@observablehq/notebook-runtime@1.2.3?module";
```

Is there an example or something else that recommended 1.0.1? If so, let us know and we'll get it up to date.

Thanks! - Tom

**Comment by tmcw** [comment]
Closing; feel free to add more details if that wasn't the fix.
