### ISSUE TITLE
FormData not supported?

### ISSUE THREAD

**Issue by ondras** [observablehq/notebook-runtime#131]
Hi,

my sample code uses `let fd = new FormData(form)`, but it fails with the *FormData is not defined* Runtime Error. I believe FormData is a standard API: https://developer.mozilla.org/en-US/docs/Web/API/FormData

Thanks,
Ondrej

**Comment by mbostock** [comment]
You can workaround this issue by using `window.FormData` in place of `FormData`. We’re planning on fixing this in the future by expanding the set of known globals.

**Comment by ondras** [comment]
@mbostock thanks for a fast reply and an explanation! :+1:
