### ISSUE TITLE
Observable UI Keyboard Shortcuts, Linux, Chromium

### ISSUE THREAD

**Issue by drom** [observablehq/notebook-runtime#133]
Here are some issues with Observable Hot Keys under Linux, Chromium.

  * `?   Show keyboard shortcuts.`
    - Does not show window when focus is on colapsed cell.
    - Help modal window don't desapeared on ESC
  *  `Alt-Shift-Down : Focus the next cell. Alt-Shift-Up: Focus the previous cell.` don't take effect.
  *  `Alt-Cmd-Up, Alt-Cmd-Down` - `Cmd` generaly not available on the PC/Linux keyboard.

**Comment by drom** [comment]
```
>Welcome to the Keyboard Debugger!
>Inspired by Mouse Debugger by Matthew Steele.
>Keyboard Debugger is best used in Full Page Mode.
>Click on the keyboard and start typing to begin.
>Begin Log...
>Keydown ↓ Key: "Alt" KeyCode: 18
>Keydown ↓ Key: "Shift" KeyCode: 16
>Keydown ↓ Key: "ArrowDown" KeyCode: 40
>Keyup   ↑ Key: "ArrowDown" KeyCode: 40
>Keyup   ↑ Key: "Meta" KeyCode: 18
>Keyup   ↑ Key: "Shift" KeyCode: 16
```

**Comment by tmcw** [comment]
Looks like those are correct. Which - unfortunately makes this a bit hard to debug. The notebook that you're using has more than once cell, I assume, so that moving focus up & down has somewhere to go? If you can, can you see if there are any errors in the console?

**Comment by drom** [comment]
Yes, multiple cells. Multiple unrelated errors like: `Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src <URL>".`

**Comment by drom** [comment]
I can't find the code responsible for the shortcut handling. Is it in this repo?

**Comment by tmcw** [comment]
The Observable application isn't on GitHub - we release source for critical components, but not the UI or API. The keyboard handling is pretty vanilla, though - [here's the relevant code](https://gist.github.com/tmcw/f02bb153e9e5034707037310912b6228), which uses CodeMirror's handling, which is in [key_events](https://github.com/codemirror/CodeMirror/blob/master/src/edit/key_events.js) and elsewhere.

**Comment by drom** [comment]
How about the keys handling outside of CodeMirror cells?
Shell navigation work on collapsed cells?
Should '?' key work on the window scale?

**Comment by mbostock** [comment]
Since this issue does not pertain to the notebook-runtime, please use the Observable forum to discuss keyboard shortcuts and other UI-related issues. Thank you! Here is a related thread:

https://talk.observablehq.com/t/keyboard-shortcuts-on-linux/846
