### ISSUE TITLE
Safari broken?

### ISSUE THREAD

**Issue by rtxanson** [observablehq/notebook-runtime#139]
Apologies if this is the wrong place for this, but it looks like beta.observablehq.com doesn't work in Safari. The inspector is giving me: 

```[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (bundle.d0adf45c7b07756dac2a22ca525cb39bcbe69b2c9a70ea0d4bcb089f960e4a79.js:2)```

**Comment by mbostock** [comment]
The right place for this is https://talk.observablehq.com/

That said, what version of Safari are you using? It works fine for me on macOS, Safari Version 11.1.2 (13605.3.8), as well as iOS.

![screen shot 2018-09-11 at 9 00 37 pm](https://user-images.githubusercontent.com/230541/45401509-c4581a00-b605-11e8-9f86-7d2545e61f45.png)

**Comment by rtxanson** [comment]
Oh great, thanks-- didn't notice that site before. I tested on an outdated version of Safari, so I guess that's my bad: `Version 9.1 (11601.5.17.1)`.  ;)
