### ISSUE TITLE
ALT-CMD-UP not working on Linux

### ISSUE THREAD

**Issue by JobLeonard** [observablehq/notebook-runtime#141]
(I hope this is the right repo to share this issue)

I suspect the `null` here should be the actual keyboard shortcut:
![image](https://user-images.githubusercontent.com/259840/46917625-8ca80d80-cfc9-11e8-9ff0-ab7f39ce2490.png)

Note, the pop-up shown when typing `?` shows `ALT-CMD-UP`:

![image](https://user-images.githubusercontent.com/259840/46917634-9fbadd80-cfc9-11e8-89fe-931df543b8f2.png)

It's just a quality-of-life issue but I'm writing a long notebook with a lot of cells and rearranging them is getting very cumbersome now to the point where I'm resorting to copying a cell, deleting it, opening a cell elsewhere and pasting it.

**Comment by mbostock** [comment]
This was fixed on October 28. Thanks for the report!
