### ISSUE TITLE
Adopt CommonMark

### ISSUE THREAD

**Issue by tmcw** [observablehq/notebook-runtime#39]
Right now we're using [marked](https://github.com/chjj/marked) as a Markdown processor, and we simply document the syntax as Markdown. marked is modeled after the markdown.pl processor, rather than the CommonMark spec.

I think it'd be good for the future™ to commit to CommonMark syntax, as there are multiple commonmark-compliant parsers (commonmark.js, remarkable, markdown-it) with compatible syntax and output, and pointing to CommonMark as 'the syntax we support' is more rigorous than referring to the rather loose original Markdown description.

**Comment by mbostock** [comment]
Moved to observablehq/notebook-stdlib#52.
