### ISSUE TITLE
Debounce?

### ISSUE THREAD

**Issue by tmcw** [observablehq/notebook-runtime#44]
I redid [this experiment](https://beta.observablehq.com/@tmcw/police-tweets), and it works really well in our environment, super simplified! But it's doing something a little performance-oriented - running a regex on a ~30k records and building a chart. So doing it for every keystroke is not that great. In another application, I'd debounce the key events to make it a bit more pleasant. Should that be part of the runtime, or just a hand-rolled method?

**Comment by mbostock** [comment]
No immediate plans here—we have a few related tools already.
