### ISSUE TITLE
constant as part of the stdlib?

### ISSUE THREAD

**Issue by tmcw** [observablehq/notebook-runtime#56]
See https://beta.observablehq.com/@tmcw/interacting-with-promises-as-values - I'm trying to discuss how one uses Promises across cell boundaries. People might want to do this so they can demo a promise-based API, or for teaching JavaScript, or they might want to have more control over when Promises are resolved. One workaround is just never crossing cell boundaries: the other is a functor/constant that returns a promise.

Is there another workaround? If this is a useful pattern, is it something we should include in the runtime?

**Comment by mbostock** [comment]
No current plans to do this, so closing.
